language: node_js
node_js:
  - "5.4"
before_script:
  - npm install -g bower
  - bower install

language: bash
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "nextweekend.co"
  endpoint: "nextweekend.co.s3-website-us-east-1.amazonaws.com"
